export * from "./home.type";
export * from "./movie.type";
export * from "./episode.type";
export * from "./common.type";
export * from "./category.type";
export * from "./news.type";
export * from "./video.type";
export * from "./star.type";
export * from "./user.type";
